name: Streamlit Filter Age App Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install streamlit  # Ensure Streamlit is installed

      - name: Set up GOOGLE_SHEET_CREDENTIALS_JSON secret
        run: echo "${{ secrets.GOOGLE_SHEET_CREDENTIALS_JSON }}" > creds.json
        env:
          GOOGLE_SHEET_CREDENTIALS_JSON: ${{ secrets.GOOGLE_SHEET_CREDENTIALS_JSON }}

      - name: Run Streamlit app
        run: streamlit run app.py --server.port 8501
        env:
          GOOGLE_SHEET_CREDENTIALS_JSON: ${{ secrets.GOOGLE_SHEET_CREDENTIALS_JSON }}
