name: Filter Age Workflow

on:
  push:
    branches:
      - main

jobs:
  filter-age:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run filter script
        run: python filter.py

      - name: Upload filtered data as artifact
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: filtered-data
          path: data/output.xlsx
